/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillFacebook,
  AiFillLinkedin,
} from "react-icons/ai";
import avatar from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.webp";
import web6 from "../public/web6.webp";
import web2 from "../public/web2.webp";
import web3 from "../public/web3.webp";
import web4 from "../public/web4.webp";
import web5 from "../public/web5.webp";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-52">
        <section className="min-h-screen">
          <nav className="flex justify-between py-12 mb-14">
            <h1 className="text-xl font-burtons">Golam Mostafa</h1>
            <ul className="flex items-center">
              <li className="text-lg mr-6 cursor-pointer">
                <BsFillMoonStarsFill />
              </li>
              <li className="bg-gradient-to-r cursor-pointer rounded-md from-cyan-500 to-teal-500 px-4 py-1 text-white">
                Resume
              </li>
            </ul>
          </nav>
          <div className="text-center space-y-10">
            <h1 className="text-5xl text-teal-600 font-medium">
              Golam Mostafa
            </h1>
            <h2 className="text-2xl">Developer and Designer</h2>
            <p className="max-w-lg leading-6 text-gray-600 text-lg mx-auto text-justify">
              Developer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking.
            </p>
          </div>
          <div className="max-w-xl my-8 mx-auto flex justify-center gap-12 text-5xl cursor-pointer text-teal-600">
            <AiFillTwitterCircle />
            <AiFillFacebook />
            <AiFillLinkedin />
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto my-20 overflow-hidden ring-4 outline-2 ring-teal-500">
            <Image src={avatar} alt="avatar" layout="fill" objectFit="cover" />
          </div>
        </section>
        <section className="mt-4">
          <div className="space-y-5">
            <h2 className="text-3xl">Services I offer</h2>
            <p className="leading-8 text-gray-800 text-md tracking-wide text-justify">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for{" "}
              <span className="text-teal-500"> agencies </span> consulted for
              <span className="text-teal-500"> startups </span> and collaborated
              with talanted people to create digital products for both business
              and consumer use.
            </p>
            <p className="leading-8 text-gray-800 text-md tracking-wide text-justify">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="py-6 flex gap-5">
            <div className="shadow-lg rounded-lg hover:shadow-xl hover:shadow-teal-100 space-y-6 text-center flex-1 bg-gradient-to-b from-teal-100 p-8">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className="inline rounded-full ring-2 ring-teal-500 p-1"
              />
              <p className="text-2xl">Beautiful Designs</p>
              <p className="text-gray-600 text-md">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <p className="text-teal-500 text-lg">Design Tools I Use</p>
              <div className="space-y-1 italic">
                <p>Photoshop</p>
                <p>Illustrator</p>
                <p>Figma</p>
                <p>Indesign</p>
              </div>
            </div>
            <div className="shadow-lg rounded-lg hover:shadow-xl hover:shadow-teal-100 space-y-6 text-center flex-1 bg-gradient-to-b from-teal-100 p-8">
              <Image
                src={code}
                width={100}
                height={100}
                alt="design"
                className="inline rounded-full ring-2 ring-teal-500 p-1"
              />
              <p className="text-2xl">Code your dream project</p>
              <p className="text-gray-600 text-md">
                Do you have an idea for your next great website? Let&apos;s make
                it a reality.
              </p>
              <p className="text-teal-500 text-lg">Design Tools I Use</p>
              <div className="space-y-1 italic">
                <p>Photoshop</p>
                <p>Illustrator</p>
                <p>Figma</p>
                <p>Indesign</p>
              </div>
            </div>
            <div className="shadow-lg rounded-lg hover:shadow-xl hover:shadow-teal-100 space-y-6 text-center flex-1 bg-gradient-to-b from-teal-100 p-8">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="design"
                className="inline rounded-full ring-2 p-1 ring-teal-500"
              />
              <p className="text-2xl">Consulting</p>
              <p className="text-gray-600 text-md">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <p className="text-teal-500 text-lg">Design Tools I Use</p>
              <div className="space-y-1 italic">
                <p>Photoshop</p>
                <p>Illustrator</p>
                <p>Figma</p>
                <p>Indesign</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="space-y-5 mt-8">
            <h2 className="text-3xl">Portfolio</h2>
            <p className="leading-8 text-gray-800 text-md tracking-wide text-justify">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for{" "}
              <span className="text-teal-500"> agencies </span> consulted for
              <span className="text-teal-500"> startups </span> and collaborated
              with talanted people to create digital products for both business
              and consumer use.
            </p>
            <p className="leading-8 text-gray-800 text-md tracking-wide text-justify">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
